spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security2
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 15000 # 15 seconds
      refresh-token:
        expiration: 86400000 # 1 day # The expiration time in milliseconds. This value is set to 1 day.

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/jwt_security
#     username: root
#     password: password
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#       # ddl-auto: create-drop
#     show-sql: false
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#         format_sql: true
#     # database: mysql
#     # database-platform: org.hibernate.dialect.PostgreSQLDialect

# application:
#   security:
#     jwt:
#       secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#       expiration: 86400000 # a day
#       refresh-token:
#         expiration: 604800000 # 7 days
